#!/usr/bin/env bash
# transfers a file from our client to a server
if [$# -lt 3]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [$# -eq 3]
then
    path_to_file=$1
    ip=$2
    user=$3
    scp -o StrictHostKeyChecking=no "path_to_file" "user@ip:~/"
else
    path_to_file=$1
    ip=$2
    user=$3
    path_to_ssh_key=$4
    scp -i "path_to_ssh_key" -o StrictHostKeyChecking=no "path_to_file" "user@ip:~/"
fi