#!/usr/bin/env bash
# Installing nginx on my server
sudo usermod -aG sudo $(whoami)
apt-get -y update
apt-get -y install nginx
rm /var/www/html/*
echo "Holberton School" >> /var/www/html/index.html
service nginx restart