#!/usr/bin/env bash
# Configure a custom 404 error page
apt-get update -y
apt-get upgrade -y
apt-get install nginx -y
echo "Ceci n'est pas une page">404_error-index.html
old="server_name _;"
new="\n\n\tlocation /error_page {\n\t\treturn 404 404_error-index.html;\n\t}\n"
sed -i "/$old/a\\$new" /etc/nginx/sites-available/default
service nginx restart
