#!/usr/bin/env bash
# Installing nginx on my server
sudo apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html

# Add redirection
old="server_name _;"
new="\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=8vPxDAMqGeI;\n\t}\n"

sed -i "/$old/a\\$new" /etc/nginx/sites-available/default

# Add header to HTTP header response

sed -i "53i add_header X-Served-By $HOSTNAME always;" /etc/nginx/sites-available/default

service nginx restart
