#!/usr/bin/env bash
# Installing HAproxy for load balancer
sudo apt-get -y update
apt-get -y install haproxy

# Make sure that HAproxy can be managed via an init script
echo "ENABLED=1">>/etc/default/haproxy

# Configure HAproxy to be able to send traffic to web-01 and web-02 servers
add_frontend="frontend aikedesign.tech\n\tbind 3.91.5.156:80\n\tbind 34.228.153.161:80\n\tdefault_backend web_servers\n"
add_backend="backend web_servers\n\tbalance roundrobin\n\tserver 3002-web-01 3.91.5.156:80\n\tserver 3002-web-02 34.228.153.161:80\n"
echo -e "$add_frontend">>/etc/haproxy/haproxy.cfg
echo -e "$add_backend">>/etc/haproxy/haproxy.cfg

service haproxy restart
