#!/usr/bin/env bash
# Make it works
pkill apache2
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo chown -R nginx:nginx /etc/nginx/
sudo chmod 644 "/etc/nginx/nginx.conf"
sudo -u nginx service nginx start
